"""
TiTiler Tile Server — Flood Risk Map
Deployed to Google Cloud Run (free tier)

Serves Cloud-Optimised GeoTIFFs directly from Cloudflare R2.
TiTiler reads COGs on-the-fly — no tile pre-generation needed.

Endpoints (auto-generated by TiTiler):
    /cog/tiles/{z}/{x}/{y}?url=...      → map tiles
    /cog/info?url=...                   → raster metadata
    /cog/statistics?url=...             → band statistics
    /cog/preview?url=...                → preview image

Environment variables:
    R2_PUBLIC_URL — public base URL of your R2 bucket
                    e.g. https://pub-<id>.r2.dev
"""

import os
from titiler.core.factory import TilerFactory
from titiler.core.errors import DEFAULT_STATUS_CODES, add_exception_handlers
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Accra Flood Risk Tile Server",
    description="COG tile server for the Greater Accra flood risk map",
    version="0.1.0",
)

# Allow the frontend (GitHub Pages) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten to your GitHub Pages URL in production
    allow_methods=["GET"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# TiTiler COG router
# ---------------------------------------------------------------------------

cog = TilerFactory()
app.include_router(cog.router, prefix="/cog", tags=["COG"])
add_exception_handlers(app, DEFAULT_STATUS_CODES)

# ---------------------------------------------------------------------------
# Convenience endpoint — returns the tile URL template for the flood risk map
# ---------------------------------------------------------------------------

R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL", "")
COG_PATH      = "rasters/flood_risk_map.cog.tif"


@app.get("/flood-risk/tile-url", tags=["Flood Risk"])
def get_tile_url():
    """Return the XYZ tile URL template for the flood risk COG."""
    if not R2_PUBLIC_URL:
        return JSONResponse(
            {"error": "R2_PUBLIC_URL environment variable not set"},
            status_code=500,
        )
    cog_url  = f"{R2_PUBLIC_URL}/{COG_PATH}"
    tile_url = (
        f"/cog/tiles/{{z}}/{{x}}/{{y}}"
        f"?url={cog_url}"
        f"&colormap_name=plasma"
        f"&rescale=0,1"
    )
    return {
        "cog_url":  cog_url,
        "tile_url": tile_url,
        "colormap": "plasma",
        "rescale":  [0, 1],
    }


@app.get("/health", tags=["System"])
def health():
    return {"status": "ok"}
